# 網站基本設定
title: "許鈺敏 醫師 | 兒童內分泌與精準醫療"
description: "「在追求公分數之前，先用數據與基因，為孩子確認健康的效益。」"
#url: "https://ymsbio.github.io"
#baseurl: "/pregrowth-website"

# 載入 Minimal Mistakes 主題與必要外掛 (這行加了 plugins 就不會當機了)
# 載入 Minimal Mistakes 主題與必要外掛
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

# 左側個人檔案設定
author:
  name: "許鈺敏 醫師"
  avatar: "/Gemini_Generated_Image_ppecwzppecwzppec.png"
  bio: "小兒遺傳新陳代謝專科 ｜<br>資料科學與大數據"
  location: "臺北醫學大學附設醫院"
  links:
    - label: "個人臉書粉專"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/grow180/"
    - label: "北醫掛號頁面"
      icon: "fas fa-fw fa-hospital"
      url: "https://www.tmuh.org.tw/team/team/04/04/040029"
    - label: "親子天下專欄"
      icon: "fas fa-fw fa-pen-nib"
      url: "https://premium.parenting.com.tw/author/303"
    - label: "商務或演講邀請"
      icon: "fas fa-fw fa-envelope"
      url: "https://forms.gle/A51KtVUcTwMXAvTy8"

# 啟用導覽列
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# 網站數據分析 (Google Analytics 4)
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-VD0PSBBP0X"
